#!/usr/bin/env bash

basedir=${PWD}
version="$(cat VERSION | tr -d '\n')"
target=${basedir}/target
repackage=${basedir}/repackage
downloads=${basedir}/downloads
file=GnuPG-${version}.dmg

rm -rf ${repackage} > /dev/null 2>&1
mkdir ${repackage}
rm -rf ${target} > /dev/null 2>&1
mkdir ${target}
mkdir ${downloads} > /dev/null 2>&1

if [ ! -f ${downloads}/${file} ]; then
  echo "curl -L -o ${download}/${file} https://sourceforge.net/projects/gpgosx/files/${file}/download"
  curl -L -o ${downloads}/${file} https://sourceforge.net/projects/gpgosx/files/${file}/download
fi

cd ${target}

if [ ! -d "/Volumes/GnuPG ${version}" ]; then
  (cd ${downloads}; hdiutil attach ${file})
fi

cp /Volumes/GnuPG\ ${version}/Install.pkg .
xar -xf Install.pkg
mkdir install
cd install
gzcat ../GnuPG.pkg/Payload | cpio -id
tar cvzf ${repackage}/gnupg-Darwin-x86_64-${version}.tar.gz *
