name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Repackage GnuPG v2 for Darwin
        run: ./repackage-gnupg
